In [ ]:
import pandas as pd
import numpy as np
import random

In [2]:
# Total number of smaple
n_total = 100

In [3]:
# proportion of male and female
p_male_ratio = 0.49
p_female_ratio = 0.51

# compute num of male and female 
n_male = int(n_total * p_male_ratio)
n_female = int(n_total * p_female_ratio)

In [4]:
# Generate the Sex column
Sex = ['MALE'] * n_male + ['FEMALE'] * n_female
# shuffle the sex column 
np.random.shuffle(Sex)

In [5]:
# Age group proportion based on 2021 dataset 

age_distribution = {
    "age_0_14": 18.3,
    "age_15_17": 3.42,
    "age_18_20": 2.28,
    "age_21_24": 6.2,
    "age_25_29": 7.0,
    "age_30_34": 7.3,
    "age_35_39": 7.0,
    "age_40_44": 6.5,
    "age_45_49": 6.2,
    "age_50_54": 6.3,
    "age_55_59": 6.1,
    "age_60_64": 5.9,
    "age_65_69": 5.1,
    "age_70_74": 4.6,
    "age_75_79": 3.2,
    "age_80_84": 2.2,
    "age_85_over": 2.1
}

for i in age_distribution.keys():
    age_distribution[i] = round(age_distribution[i] * 0.01, 4)

# Compute num of each age group
num_ageGroup_list = []

for i in age_distribution.keys():
    num_of_a_ageGroup = int(age_distribution[i] * n_total)
    num_ageGroup_list.append(num_of_a_ageGroup)

# Create a list for age label
age_labels = list(age_distribution.keys())

# Generate the Age column
Age = []
for label, count in zip(age_labels, num_ageGroup_list):
    Age.extend([label]*count)

# Check if the number of label value in column Age = n_total or not, if not, fill in the random number to reach the n_total
remaining = n_total - len(Age)
if remaining > 0:
    Age.extend(np.random.choice(age_labels, remaining))

# Shuffle the value in the Age column
np.random.shuffle(Age)

In [42]:
# Income generation based on regression result of (Age + Sex) and (Age * Sex) 
regression_results = {
    "intercept": -2505.874,
    "intercept_with_interaction": 1132.80,
    "Male": 8245.466,
    "Male_with_interaction": 58.45,
    "age_14_and_under": -4497.592,
    "age_14_and_under_with_interaction": 50.75,
    "age_15_to_17": 1244.541,
    "age_15_to_17_with_interaction": 1637.80,
    "age_18_to_20": 4935.541,
    "age_21_to_24": 10991.641,
    "age_25_to_29": 19184.141,
    "age_30_to_34": 30440.441,
    "age_35_to_39": 38652.641,
    "age_40_to_44": 42972.541,
    "age_45_to_49": 44856.341,
    "age_50_to_54": 45082.841,
    "age_55_to_59": 43672.341,
    "age_60_to_64": 37610.641,
    "age_65_to_69": 24346.141,
    "age_70_to_74": 12628.141,
    "age_75_to_79": 7503.041,
    "age_75_to_79_with_interaction": 6745.00,
    "age_80_to_84": 5364.741,
    "age_80_to_84_with_interaction": 5382.80,
    "age_85_and_over": 5639.341,
    "age_85_and_over_with_interaction": 5996.80
}

# Compute the expected median income per year for each age group
income_14_male = round(regression_results["intercept"] + regression_results['Male'] + regression_results['age_14_and_under'])
income_14_female = round(regression_results['intercept_with_interaction'] + regression_results['age_14_and_under_with_interaction'])

income_15_17_male = round(regression_results['intercept'] + regression_results['Male'] + regression_results['age_15_to_17'])
income_15_17_female = round(regression_results['intercept_with_interaction'] + regression_results['age_15_to_17_with_interaction'])

income_18_20_male = round(regression_results["intercept"] + regression_results['Male'] + regression_results['age_18_to_20'])
income_18_20_female = round(regression_results["intercept"] + regression_results['age_18_to_20'])

income_21_24_male = round(regression_results["intercept"] + regression_results['Male'] + regression_results['age_21_to_24'])
income_21_24_female = round(regression_results["intercept"] + regression_results['age_21_to_24'])

income_25_29_male = round(regression_results["intercept"] + regression_results['Male'] + regression_results['age_25_to_29'])
income_25_29_female = round(regression_results["intercept"] + regression_results['age_25_to_29'])

income_30_34_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_30_to_34"])
income_30_34_female = round(regression_results["intercept_with_interaction"] + regression_results["age_30_to_34"])

income_35_39_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_35_to_39"])
income_35_39_female = round(regression_results["intercept"] + regression_results["age_35_to_39"])

income_40_44_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_40_to_44"])
income_40_44_female = round(regression_results["intercept"] + regression_results["age_40_to_44"])

income_45_49_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_45_to_49"]) # 50596 vs real: 51,000 - 57,000
income_45_49_female = round(regression_results["intercept"] + regression_results["age_45_to_49"]) # 42350 vs real: 34,000 - 39,000

income_50_54_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_50_to_54"]) # 50822 vs real: 54,000 -59,000
income_50_54_female = round(regression_results["intercept"] + regression_results["age_50_to_54"]) # 42577 vs real: 35,000 - 40,000

income_55_59_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_55_to_59"]) # 49412 vs real: 50,000 -57,000
income_55_59_female = round(regression_results["intercept"] + regression_results["age_55_to_59"]) # 41166 vs real: 34,000 - 39,000

income_60_64_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_60_to_64"]) # 43350
income_60_64_female = round(regression_results["intercept"] + regression_results["age_60_to_64"]) # 35105

income_65_69_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_65_to_69"])
income_65_69_female = round(regression_results["intercept"] + regression_results["age_65_to_69"])

income_70_74_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_70_to_74"])
income_70_74_female = round(regression_results["intercept"] + regression_results["age_70_to_74"])

income_75_79_male = round(regression_results["intercept"] + regression_results["Male"] + regression_results["age_75_to_79"])
income_75_79_female = round(regression_results["intercept_with_interaction"] + regression_results["age_75_to_79_with_interaction"])

income_80_84_male = round(regression_results["intercept_with_interaction"] + regression_results["Male_with_interaction"] + regression_results["age_80_to_84_with_interaction"])
income_80_84_female = round(regression_results["intercept_with_interaction"] + regression_results["age_80_to_84_with_interaction"])

income_85_over_male = round(regression_results["intercept_with_interaction"] + regression_results["Male_with_interaction"] + regression_results["age_85_and_over_with_interaction"])
income_85_over_female = round(regression_results["intercept_with_interaction"] + regression_results["age_85_and_over_with_interaction"])

# steore the corresponding median for each age to a dict

income_by_age_sex = {
    "age_0_14": {
        "MALE": income_14_male, 
        "FEMALE": income_14_female
    },
    "age_15_17": {
        "MALE": income_15_17_male,
        "FEMALE": income_15_17_female
    },
    "age_18_20": {
        "MALE": income_18_20_male,
        "FEMALE": income_18_20_female
    },
    "age_21_24": {
        "MALE": income_21_24_male,
        "FEMALE": income_21_24_female
    },
    "age_25_29": {
        "MALE": income_25_29_male,
        "FEMALE": income_25_29_female
    },
    "age_30_34": {
        "MALE": income_30_34_male,
        "FEMALE": income_30_34_female
    },
    "age_35_39": {
        "MALE": income_35_39_male,
        "FEMALE": income_35_39_female
    },
    "age_40_44": {
        "MALE": income_40_44_male,
        "FEMALE": income_40_44_female
    },
    "age_45_49": {
        "MALE": income_45_49_male,
        "FEMALE": income_45_49_female
    },
    "age_50_54": {
        "MALE": income_50_54_male,
        "FEMALE": income_50_54_female
    },
    "age_55_59": {
        "MALE": income_55_59_male,
        "FEMALE": income_55_59_female
    },
    "age_60_64": {
        "MALE": income_60_64_male,
        "FEMALE": income_60_64_female
    },
    "age_65_69": {
        "MALE": income_65_69_male,
        "FEMALE": income_65_69_female
    },
    "age_70_74": {
        "MALE": income_70_74_male,
        "FEMALE": income_70_74_female
    },
    "age_75_79": {
        "MALE": income_75_79_male,
        "FEMALE": income_75_79_female
    },
    "age_80_84": {
        "MALE": income_80_84_male,
        "FEMALE": income_80_84_female
    },
    "age_85_over": {
        "MALE": income_85_over_male,
        "FEMALE": income_85_over_female
    }
}

In [43]:
syn_dataset  = pd.DataFrame({
    'Sex': Sex,
    'Age': Age
})

In [ ]:
syn_dataset["Median_income_per_year"] = syn_dataset.apply(
    lambda row: income_by_age_sex[row["Age"]][row["Sex"]],
    axis=1
)

# apply a random standard deviation to the income colum
pct_changes = [-0.15, -0.1, -0.08, -0.06, -0.04, -0.02, -0.015, -0.01, -0.005, 0, 0.005, 0.01, 0.015, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15]
syn_dataset["Median_income_per_year"] = syn_dataset["Median_income_per_year"].apply(lambda x: x * (1 + np.random.choice(pct_changes)))

In [47]:
syn_dataset.head(15)

       Sex        Age  Median_income_per_year
0   FEMALE  age_25_29               17345.120
1   FEMALE   age_0_14                1189.920
2   FEMALE   age_0_14                1089.280
3     MALE  age_21_24               16647.345
4     MALE   age_0_14                1117.800
5     MALE  age_50_54               54887.760
6   FEMALE  age_30_34               31730.865
7     MALE  age_65_69               31289.440
8   FEMALE  age_40_44               36420.300
9   FEMALE  age_70_74               11134.200
10  FEMALE  age_15_17                2937.260
11    MALE  age_75_79               14302.440
12    MALE   age_0_14                1341.360
13  FEMALE  age_40_44               40669.335
14  FEMALE  age_60_64               36509.200

In [48]:
import statsmodels.formula.api as smf

# run the statistical model to compare the real and synthetic data

# simple linear reg age + sex
simple_reg_model = smf.ols('Median_income_per_year ~ Sex + Age', data= syn_dataset).fit()
simple_reg_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     Median_income_per_year   R-squared:                       0.980
Model:                                OLS   Adj. R-squared:                  0.975
Method:                     Least Squares   F-statistic:                     232.2
Date:                    Mon, 21 Apr 2025   Prob (F-statistic):           7.17e-62
Time:                            17:58:09   Log-Likelihood:                -925.95
No. Observations:                     100   AIC:                             1888.
Df Residuals:                          82   BIC:                             1935.
Df Model:                              17
Covariance Type:                nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept          -1756.4424    728.622     -2.411      0.018   -3205.903    -306.982
Sex[T.MALE]         5892.5370    610.769      9.648      0.000    4677.523    7107.551
Age[T.age_15_17]    3837.5301   1753.217      2.189      0.031     349.823    7325.238
Age[T.age_18_20]    5502.7301   1551.439      3.547      0.001    2416.423    8589.037
Age[T.age_21_24]    1.208e+04   1323.072      9.131      0.000    9449.433    1.47e+04
Age[T.age_25_29]    1.941e+04   1250.946     15.513      0.000    1.69e+04    2.19e+04
Age[T.age_30_34]    3.375e+04   1250.946     26.982      0.000    3.13e+04    3.62e+04
Age[T.age_35_39]    3.788e+04   1269.072     29.851      0.000    3.54e+04    4.04e+04
Age[T.age_40_44]    4.101e+04   1357.858     30.202      0.000    3.83e+04    4.37e+04
Age[T.age_45_49]    4.613e+04   1326.982     34.763      0.000    4.35e+04    4.88e+04
Age[T.age_50_54]    4.681e+04   1250.946     37.418      0.000    4.43e+04    4.93e+04
Age[T.age_55_59]     4.31e+04   1326.982     32.482      0.000    4.05e+04    4.57e+04
Age[T.age_60_64]    3.909e+04   1323.072     29.543      0.000    3.65e+04    4.17e+04
Age[T.age_65_69]     2.48e+04   1420.150     17.461      0.000     2.2e+04    2.76e+04
Age[T.age_70_74]    1.371e+04   1558.935      8.796      0.000    1.06e+04    1.68e+04
Age[T.age_75_79]    9982.4334   1753.217      5.694      0.000    6494.726    1.35e+04
Age[T.age_80_84]    4077.5111   1753.217      2.326      0.023     589.804    7565.219
Age[T.age_85_over]  8743.8424   2114.133      4.136      0.000    4538.159    1.29e+04
==============================================================================
Omnibus:                        1.295   Durbin-Watson:                   2.349
Prob(Omnibus):                  0.523   Jarque-Bera (JB):                1.104
Skew:                           0.002   Prob(JB):                        0.576
Kurtosis:                       2.485   Cond. No.                         12.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""