只用每个特征的分布和均值，不考虑联合分布。

初始化一批样本，只赋予收入数值，不赋特征标签。

对每个特征变量的每个类别，从样本池中选出一批（如800个），使得这批样本的平均收入尽量接近该类别的真实均值，并赋予该类别标签。

最终只保留那些被所有特征变量都赋值的样本（如2000个），作为生成数据。

In [ ]:
import pandas as pd

In [5]:
# 输入源数据csv，输出该feature的收入分布
def compute_feature_income(df):
    group_col = 'feature'
    weight_col = 'number_of_jobs'
    income_col = 'median_income'
    prob = df.groupby(group_col)[weight_col].sum()
    prob = prob / prob.sum()
    def weighted_mean(x):
        return (x[weight_col] * x[income_col]).sum() / x[weight_col].sum()
    mean_income = df.groupby(group_col).apply(weighted_mean)
    stats = pd.DataFrame({
        'prob': prob,
        'mean_income': mean_income
    })
    return stats.dropna()

In [6]:
csv_path = r"E:\git\DataScience_Project_Team_25\data\pre_transform\Industry_gender.csv"
df = pd.read_csv(csv_path)
compute_feature_income(df)

C:\Users\Seans\AppData\Local\Temp\ipykernel_24188\2892103138.py:9: RuntimeWarning: invalid value encountered in scalar divide
  return (x[weight_col] * x[income_col]).sum() / x[weight_col].sum()

                                                     prob    mean_income
feature
Accommodation and food services                  0.085147    7929.008206
Administrative and support services              0.102027   13199.965966
Agriculture, forestry and fishing                0.023760    8697.652653
Arts and recreation services                     0.021877    9091.301805
Construction                                     0.077830   37007.952451
Education and training                           0.080523   32231.069328
Electricity, gas, water and waste services       0.007602   81084.375104
Finance and insurance services                   0.042551   42588.009914
Health care and social assistance                0.129402   38370.979234
Information media and telecommunications         0.015267   37332.841685
Manufacturing                                    0.057128   46728.556643
Mining                                           0.012592  109933.654861
Professional, scientific and technical services  0.085867   41424.760374
Public administration and safety                 0.061133   64293.431601
Rental, hiring and real estate services          0.020472   29011.762885
Retail trade                                     0.096355   18644.661894
Transport, postal and warehousing                0.042342   33473.381462
Wholesale trade                                  0.038126   46583.570871